version: '3.9'

name: wallet-ecosystem
services:

  wallet-enterprise-vid-issuer:
    container_name: wallet-enterprise-vid-issuer
    hostname: wallet-enterprise-vid-issuer
    build:
      context: $PWD/wallet-enterprise
      dockerfile: development.Dockerfile
    image: wallet-enterprise
    restart: always
    ports:
      - 8003:8003
    depends_on:
      wallet-db:
        condition: service_healthy
    volumes:
      - ./wallet-enterprise:/home/node/app
      - ./wallet-enterprise-configurations/acme-verifier/config/config.development.ts:/home/node/app/config/config.development.ts
      - ./wallet-enterprise-configurations/acme-verifier/keys:/home/node/app/keys
      - ./wallet-enterprise-configurations/acme-verifier/views/index.pug:/home/node/app/views/index.pug
      - ./wallet-enterprise-configurations/acme-verifier/views/header.pug:/home/node/app/views/header.pug
      - ./wallet-enterprise-configurations/acme-verifier/src/configuration:/home/node/app/src/configuration
      - ./wallet-enterprise-configurations/acme-verifier/public/styles/styles.css:/home/node/app/public/styles/styles.css
      - ./wallet-enterprise-configurations/acme-verifier/public/images:/home/node/app/public/images
      - /home/node/app/dist
      - /home/node/app/node_modules
      - ./.vscode/:/home/node/app/.vscode
    deploy:
      resources:
          limits:
            memory: 1G

  wallet-enterprise-diploma-issuer:
    container_name: wallet-enterprise-diploma-issuer
    hostname: wallet-enterprise-diploma-issuer
    build:
      context: $PWD/wallet-enterprise
      dockerfile: development.Dockerfile
    image: wallet-enterprise
    restart: always
    ports:
      - 8000:8000
    depends_on:
      wallet-db:
        condition: service_healthy
    volumes:
      - ./wallet-enterprise:/home/node/app
      - ./wallet-enterprise-configurations/diploma-issuer/config/config.development.ts:/home/node/app/config/config.development.ts
      - ./wallet-enterprise-configurations/diploma-issuer/keys:/home/node/app/keys
      - ./wallet-enterprise-configurations/diploma-issuer/src/configuration:/home/node/app/src/configuration
      - ./wallet-enterprise-configurations/diploma-issuer/views/issuer/login.pug:/home/node/app/views/issuer/login.pug
      - ./wallet-enterprise-configurations/diploma-issuer/public/styles/styles.css:/home/node/app/public/styles/styles.css
      - ./wallet-enterprise-configurations/diploma-issuer/public/images:/home/node/app/public/images
      - /home/node/app/dist
      - /home/node/app/node_modules
      - ./.vscode/:/home/node/app/.vscode
    deploy:
      resources:
          limits:
            memory: 1G

  wallet-enterprise-acme-verifier:
    container_name: wallet-enterprise-acme-verifier
    hostname: wallet-enterprise-acme-verifier
    build:
      context: $PWD/wallet-enterprise
      dockerfile: development.Dockerfile
    image: wallet-enterprise
    restart: always
    ports:
      - 8005:8005
    depends_on:
      wallet-db:
        condition: service_healthy
    volumes:
      - ./wallet-enterprise:/home/node/app
      - ./wallet-enterprise-configurations/acme-verifier/config/config.development.ts:/home/node/app/config/config.development.ts
      - ./wallet-enterprise-configurations/acme-verifier/keys:/home/node/app/keys
      - ./wallet-enterprise-configurations/acme-verifier/views/index.pug:/home/node/app/views/index.pug
      # - ./wallet-enterprise-configurations/acme-verifier/views/header.pug:/home/node/app/views/header.pug
      # - ./wallet-enterprise-configurations/acme-verifier/views/verifier/public_definitions.pug:/home/node/app/views/verifier/public_definitions.pug
      # - ./wallet-enterprise-configurations/acme-verifier/views/verifier/QR.pug:/home/node/app/views/verifier/QR.pug
      # - ./wallet-enterprise-configurations/acme-verifier/views/verifier/success.pug:/home/node/app/views/verifier/success.pug
      - ./wallet-enterprise-configurations/acme-verifier/src/configuration:/home/node/app/src/configuration
      - ./wallet-enterprise-configurations/acme-verifier/public/styles/styles.css:/home/node/app/public/styles/styles.css
      - ./wallet-enterprise-configurations/acme-verifier/public/images:/home/node/app/public/images
      - /home/node/app/dist
      - /home/node/app/node_modules
      - ./.vscode/:/home/node/app/.vscode
    deploy:
      resources:
          limits:
            memory: 1G
  
  wallet-db:
    image: mariadb
    container_name: wallet-db
    hostname: wallet-db
    restart: always
    ports:
      - 3307:3307
    expose: 
      - 3307
    environment:
      MARIADB_HOST: wallet-db
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: myuser
      MARIADB_PASSWORD:
      MYSQL_TCP_PORT: 3307
      MYSQL_UNIX_PORT: 3307
    healthcheck:
      test: ["CMD", "mariadb" ,"-uroot", "-proot", "--protocol=TCP", "-hlocalhost", "--port=3307",  "-estatus"]
      timeout: 20s
      retries: 10
    volumes:
      # persist data files into `datadir` volume managed by docker
      - datadir:/var/lib/mysql
      # bind-mount any sql files that should be run while initializing
      - ./db-setup/scripts/:/docker-entrypoint-initdb.d/

  wallet-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: wallet-phpmyadmin
    hostname: wallet-phpmyadmin
    ports:
      - 8081:8081
    environment:
      APACHE_PORT: 8081
      PMA_HOST: wallet-db
      PMA_PORT: 3307

  wallet-backend-server:
    container_name: wallet-backend-server
    build:
      context: $PWD/wallet-backend-server
      dockerfile: development.Dockerfile
    image: wallet-backend-server
    restart: always
    ports:
      - 8002:8002
    depends_on:
      wallet-db:
        condition: service_healthy
    volumes:
      - ./wallet-backend-server:/home/node/app
      - /home/node/app/dist
      - /home/node/app/node_modules
      - ./.vscode/:/home/node/app/.vscode
    deploy:
      resources:
          limits:
            memory: 1G
  wallet-frontend:
    build:
      context: $PWD/wallet-frontend
      dockerfile: development.Dockerfile
    image: wallet-frontend
    container_name: wallet-frontend
    hostname: wallet-frontend
    ports:
      - 3000:3000
    volumes:
      - $PWD/wallet-frontend:/home/node/app
      - /home/node/app/node_modules
      - ./.vscode/:/home/node/app/.vscode

volumes:
  datadir:
  cache:
    driver: local
